language: python
python:
- '2.7'
install:
- pip install .
script:
- echo ':)'
before_deploy:
- wget https://github.com/jgm/pandoc/releases/download/1.19.1/pandoc-1.19.1-1-amd64.deb
  -O $TRAVIS_BUILD_DIR/pandoc.deb
- sudo dpkg -i $TRAVIS_BUILD_DIR/pandoc.deb
- rm $TRAVIS_BUILD_DIR/pandoc.deb
- pandoc --from=markdown --to=rst --output=$TRAVIS_BUILD_DIR/README.rst README.md
deploy:
- provider: pypi
  distributions: sdist bdist_wheel
  server: https://test.pypi.org/legacy/
  skip_cleanup: true
  user: algrebe
  password:
    secure: "t8mVu/S72mSZ5ZCRAh6c4U0Ulxrg4ttEgd/iwGJj1I/FrcLdrq0ky9hvIs9QTcesF/G1ej8f1BWu/3ihNTwZfGPZgM6ZWrUNaaU9EQvc5tQTslg0vYKKjGwa1e1/O9OdE1GLvKdZsNatsOPlHaFRjn6zXrSkPEyZpzQYy7CLkbzDq9R4mD5bnDP0gtZtUZNPTL/tp6qg7EN3FNaYaX/1KtBccE9wzzrQWY75urx2gICtdG5CxAuDjNnW/ncYDTbcKINUjo9s9+6lBv+nfIi+lxF/WAiyh94fKBjhGcGG9/1AXPvgWoqBGUK6GCRkOsntmoyNG7HS+e0z4+qR1S+rWFvJ4kSqP3g4cdde0ZOu0vASNWkZwHY8BfL3HDGMukkzy8XanOKHO6HgRNU3VzJkayU+lqRTpso9WAXKx4F0VYZaByjoHQ2ZkfF9VMK5GJ1Tyefj81zTVc6VTMd8FzN7gvonHQe/Kq+tMIhXniOE5GaqiJyxzaK5kj0AP/KV+Vbo01noCzYxfLvmO8xonQ/tRxzsqAFqyk+mrTWukOEMkMJr6g59ifMZjoBsGv8FF5pZThFB9yWJjvpucN0N6GD/QnJVd13iidXGWOuX6J4hkiN07ewuHpgmtOa6n/EPJ3yxAXAvoFjVehqtLy62OYT8zsFUwZHnvNnrnPXebKpysJw="
  on:
    branch: test.pypi.org
    tags: false
- provider: pypi
  distributions: sdist bdist_wheel
  server: https://upload.pypi.org/legacy/
  skip_cleanup: true
  user: algrebe
  password:
    secure: "h4jG25YBdUUjdoMAqKiJznOiXTyQzx7u3fh7/RgiVWoxtYYQDniKYjP4Wu2VeF62yGhXSUkDUCJqXo1jacw3HhmLskf6HtzALrtqQx7hb7UT0frIgoIRT3wF2hO8YpsF3VnQ1vC5ElOmGH6YeYffyoMWrdeUNt1oAvydw/PTdIrV2vEEfG4ESQBMZoi09JR01wk2Cjexe7psgKl4fHbL7fn+Z7dgrTQ0LccVXRjgn53CsJPk8vFkU9wFPvYsjRbewxx3/bmHtkTUA0CmitPsNUiuKJ+i7e6Vr2lsLAEqDl+Mw0bQt4fmY2wVUH8EiSR/GyZdBfDsfeP34dvkpgOFNRtHHskHSjMfOqlFeukh4TWIfsWiGEQwqM754bF1Irbq8ZqAKtTb851gIBt3KNwejP/iGQf9ResDLdYjAAkI6wJAWqXbN6VW382ayTBF0RolL4irFB5rSXuUnU+gDDVlwU1Y9mytFqDUNfNb61fKAzA2xsqZAllKTYpQvxTexEZUud9uLGKyAjb+91i4fJReOfOFlMrOHdcCgrq2DgMLsLcP/4fkrh/npt/cwDqmBCsjtQ5btyxsrQ2sWYVgauuVsY9we2PjqJI3rXGyg2ri5COo5FyguWh6LV0r4ZOm4cD4DJSKlmmlN5ae5r7e/o6X/yO5JlllejNXoXDawRAADYI="
  on:
    branch: master
    tags: true
