language: python
python:
- '2.7'
install:
- pip install .
script:
- echo ':)'
before_deploy:
- wget https://github.com/jgm/pandoc/releases/download/1.19.1/pandoc-1.19.1-1-amd64.deb
  -O $TRAVIS_BUILD_DIR/pandoc.deb
- sudo dpkg -i $TRAVIS_BUILD_DIR/pandoc.deb
- rm $TRAVIS_BUILD_DIR/pandoc.deb
- pandoc --from=markdown --to=rst --output=$TRAVIS_BUILD_DIR/README.rst README.md
deploy:
- provider: pypi
  distributions: sdist bdist_wheel
  server: https://testpypi.python.org/legacy/
  skip_cleanup: true
  user: algrebe
  password:
    secure: "t8mVu/S72mSZ5ZCRAh6c4U0Ulxrg4ttEgd/iwGJj1I/FrcLdrq0ky9hvIs9QTcesF/G1ej8f1BWu/3ihNTwZfGPZgM6ZWrUNaaU9EQvc5tQTslg0vYKKjGwa1e1/O9OdE1GLvKdZsNatsOPlHaFRjn6zXrSkPEyZpzQYy7CLkbzDq9R4mD5bnDP0gtZtUZNPTL/tp6qg7EN3FNaYaX/1KtBccE9wzzrQWY75urx2gICtdG5CxAuDjNnW/ncYDTbcKINUjo9s9+6lBv+nfIi+lxF/WAiyh94fKBjhGcGG9/1AXPvgWoqBGUK6GCRkOsntmoyNG7HS+e0z4+qR1S+rWFvJ4kSqP3g4cdde0ZOu0vASNWkZwHY8BfL3HDGMukkzy8XanOKHO6HgRNU3VzJkayU+lqRTpso9WAXKx4F0VYZaByjoHQ2ZkfF9VMK5GJ1Tyefj81zTVc6VTMd8FzN7gvonHQe/Kq+tMIhXniOE5GaqiJyxzaK5kj0AP/KV+Vbo01noCzYxfLvmO8xonQ/tRxzsqAFqyk+mrTWukOEMkMJr6g59ifMZjoBsGv8FF5pZThFB9yWJjvpucN0N6GD/QnJVd13iidXGWOuX6J4hkiN07ewuHpgmtOa6n/EPJ3yxAXAvoFjVehqtLy62OYT8zsFUwZHnvNnrnPXebKpysJw="
  on:
    branch: master
    tags: false
- provider: pypi
  distributions: sdist bdist_wheel
  skip_cleanup: true
  user: algrebe
  password:
    secure: kDJlXU3rZuPdSeHAjgVzYAZgn3cpxfxUbpYP6Ec7UysH9zQDr9e/57sZ+S6FRAON4Ki5qQvlR35h4FAWQ1uwcDwWgOhJZtojKfyOw7vo1of0ncCGSnRuhDex4SqmMZWPrQIFZsWjjnu5XxqGbQ8/9z35txtDlbFeH72Lk/udqyPqwP6KXi3WgCaAPITUsc88D/yfBZISGhLF0zze9Os8mPeElLw7SVfoan5B0mQyCfJDa3yH7vrvqgGi59NxUzZyIS+m1H4533+4JlE6KVuY+C0e3TL82ecSY8TjVogC4juMBUlOoHSoiplmF46NyW9VxvhX3fbRl06XdRBJhxdFP75nJu8+HrKHzGY/Yh4nuU+uZ2HdOk2T6JgMxnsX0qz1HwcTfbgq23jzqq+DSa1glUyaMNFpfcDnfLDoSkh0vxBK2/inpWFLt7FRKRy0dmViCdMH0x4nl87PUJdOAsasB+F5cL3imOGkovzW6J/pkOSqWM+++rtjn/avOH5w0/hm3P09D2nt7KNJesVba5vG4T3ugqcN/D5bwhoJngbhqqf0R1I7rNXCqHPdHJA/InvHfTPwcxXlckN9DtkCi/8SSuiZdGt6Qdj2nKIbw43IfxFHVy6skX3qOCRtGZno2WS+cgeBPSmMV8Fze/xOhrgBdRPQG+ZJPtN8wUAFBGKhOaQ=
  on:
    branch: master
    tags: true
